### ISSUE TITLE
Distribute in Free/Libre/Open Web Font Libraries 

### ISSUE THREAD

**Issue by davelab6** [potasiyam/Kalpurush#1]
I'd love to see this font more widely available on the various FLO web font libraries, such as Brick, Open Font Library, Google Fonts, etc. 

However, the GPL isn't ideal for web font distribution because of the heavy source provision terms. 

I recommend the SIL Open Font License (recognized as a FLO license by FSF and OSI) without a reserved font name :)

**Comment by davelab6** [comment]
In fact inside the font file, the licensing is indicated as OFL:

<img width="1920" alt="screen shot 2015-11-24 at 23 28 17" src="https://cloud.githubusercontent.com/assets/261579/11373054/093040b8-9303-11e5-9b4d-c136d1792010.png">

**Comment by potasiyam** [comment]
Yes, this font is under OFL already. :)

**Comment by davelab6** [comment]
Please include an OFLtxt or LICENSE.txt file and then close this issue :)
